- name: Configure Alert Publisher via Cloudera Manager API and restart
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Send Alert Publisher config to Cloudera Manager API
      ansible.builtin.uri:
        url: "https://{{ cod_cm_server_fqdn }}:7183/api/v49/cm/service/roleConfigGroups/mgmt-ALERTPUBLISHER-BASE/config"
        method: PUT
        headers:
          "Content-Type": "application/json"
        body_format: json
        body: "{{ lookup('template', '/tmp/alert-publisher-configs1.json') }}"
        user:  "{{ api_username }}"
        password:   "{{ api_password }}"
        force_basic_auth: yes
        validate_certs: no
      register: config_response

    - name: Debug API response
      ansible.builtin.debug:
        var: config_response
